### ISSUE TITLE
Python version from current environment not picked up?

### ISSUE THREAD

**Issue by OliverSchmitz** [computationalgeography/lue#114]
When using 3.6 in a virtualenv environment I get at configure stage the system version:
cmake  -DLUE_BUILD_ALL:BOOL=TRUE -DLUE_BUILD_PYTHON_API:BOOL=TRUE -DLUE_BUILD_TEST:BOOL=TRUE -DLUE_BUILD_DOCUMENTATION:BOOL=TRUE  ~/lue

-- Found PythonInterp: /usr/bin/python3.7 (found version "3.7") 
-- Found PythonLibs: python3.7m
-- - /usr/bin/python3.7

which fails later on while compiling due to missing headers.
Adding -DPYTHON_EXECUTABLE=/home/foo/py36/bin/python 
works, but that was not necessary earlier iirc

**Comment by kordejong** [comment]
Can you try with passing this option: `-DPYBIND11_PYTHON_VERSION=3.7`. I reworked the Python detection stuff last week.

**Comment by kordejong** [comment]
I think this is not relevant anymore. Please re-open if it is.
