### ISSUE TITLE
Add ifthenelse

### ISSUE THREAD

**Issue by OliverSchmitz** [computationalgeography/lue#310]

**Comment by kordejong** [comment]
`ifthenelse` in PCRaster corresponds with `where` in LUE. `where(condition, true_expression, false_expression)` is supported. `where(condition, true_expression)` overload needs to be added. After that, wrappers need to be created for the `lue.framework` submodule.

**Comment by OliverSchmitz** [comment]
ok, thanks. ifthen is less relevant for now
