### ISSUE TITLE
Revisit compiler definitions related to boost

### ISSUE THREAD

**Issue by kordejong** [computationalgeography/lue#426]
Some definitions seem to be set while they shouldn't (anymore).

`-DBOOST_ALL_DYN_LINK -DBOOST_ALL_NO_LIB`

**Comment by OliverSchmitz** [comment]
you might only need `BOOST_TEST_DYN_LINK` to link tests

**Comment by kordejong** [comment]
Except for `Boost_NO_BOOST_CMAKE TRUE`, no Boost related settings is explicitly set by the LUE CMake scripts anymore.
Fixed some time ago, as part of some other ticket.
