### ISSUE TITLE
Please add boolean and nominal operations!

### ISSUE THREAD

**Issue by edwinkost** [computationalgeography/lue#466]
This should be an equivalent of pcraster.boolean(arg)
Thanks.

**Comment by kordejong** [comment]
LUE does not understand value scales. It does understand element types (unsigned integers, signed integers, floating points, all of different sizes). I think what you want are type casts, to convert from an integer to a float for example. Can you provide an example of what you want to achieve? Maybe we need the cast operation, or maybe something else.

**Comment by edwinkost** [comment]
Hi Kor. I understand. I think you can ignore this pull request. Yet, perhaps, could you please point me regarding any functions to convert integers to floats, and vice versa. Thanks in advance.

**Comment by kordejong** [comment]
You can currently cast from `uint64` and `int64` to either `float32` or `float64` (using `lfr.cast`). It is relatively easy to add support for more casts, but ideally, you shouldn't need them. Before adding support for more casts I would be interested in understanding the use case for them.
