### ISSUE TITLE
from_numpy with MV argument changes array data type

### ISSUE THREAD

**Issue by OliverSchmitz** [computationalgeography/lue#471]
```
in_np_array = np.ones((5,5), dtype=np.float32) * 9
array = lfr.from_numpy(in_np_array, partition_shape, 1)
```
array then is a ```PartitionedArray<uint8, 2>{shape=(5, 5), shape_in_partitions=(1, 1)}``` while I'd hope for a float32

seems that passing 1.0 instead works

using array np.int32 and MV 1.0 returns a float32

**Comment by kordejong** [comment]
Yes, that's confusing. The element type of the output array should always be the same as the element type of the input array. The no-data value passed in must be of the same / similar type as the elements in the input array.
