### ISSUE TITLE
Please add support for mold

### ISSUE THREAD

**Issue by OliverSchmitz** [computationalgeography/lue#476]
adding
-D CMAKE_EXE_LINKER_FLAGS="-fuse-ld=mold" -D CMAKE_SHARED_LINKER_FLAGS="-fuse-ld=mold"
might improve time to link, now fails to build

**Comment by kordejong** [comment]
See also:
- https://www.reddit.com/r/cpp/comments/v344th/using_the_mold_linker_for_fun_and_3x8x_link_time

**Comment by kordejong** [comment]
On velocity I use:

```cmake
set(CMAKE_EXE_LINKER_FLAGS_INIT "-fuse-ld=mold")  # gcc >=12.1.0                                               
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-fuse-ld=mold")  # gcc >=12.1.0
```
The generated executables contain proof that mold was used to link them:

```bash
$ readelf -p .comment lue_hdf5_group_test

String dump of section '.comment':
  [     0]  GCC: (GNU) 4.8.5 20150623 (Red Hat 4.8.5-44)
  [    2d]  mold 1.3.0 (compatible with GNU ld)
  [    51]  GCC: (GNU) 11.3.0
```
