### ISSUE TITLE
Add support for negative inflow to `kinematic_wave`

### ISSUE THREAD

**Issue by kordejong** [computationalgeography/lue#524]
Lateral inflow represents the addition of water (e.g. precepitation), or removal of water (e.g. infiltration, pumping). Very comparable with `accu_threshold`. The outflow passed in (negative inflow) is a maximum / potential value and may be different from what is actually removed from the cell.

We could add a second return value containing the actual amount of water removed, given the actual amount of water available in each cell. Until then, it is impossible for users to check the water budget when less water is removed than potentially can be removed. See #527 

Lateral inflow can be negative. Make sure the actual outflow (negative inflow) is not larger than the actual amount of water in the cell.

**Comment by saeb-faraji-gargari** [comment]
For guess() I found the following line

 _lue_hpx_assert(discharge_guess > Float{0});_

```
Float guess() const
                {
                    // Small, but not zero!
                    Float discharge_guess{1e-30};

                    ...

                    lue_hpx_assert(discharge_guess > Float{0});

                    return discharge_guess;
                }
```
calculated _discharge_guess_ could be negative in which case it should be set to a non-zero value

Revising the code as follows may help 

```
Float guess() const
                {
                    // Small, but not zero!
                    Float min_discharge_guess{1e-30};
                    Float discharge_guess{min_discharge_guess};

                    ...

                    return std::max(discharge_guess,min_discharge_guess}
                }
```

**Comment by kordejong** [comment]
Yes, thanks @saeb-faraji-gargari,  that was one of the changes I made yesterday. See my changes in the draft PR. It is not finished yet, but negative lateral inflows are supported now.
