### ISSUE TITLE
Add M1 macOS runner to C/I builds

### ISSUE THREAD

**Issue by kordejong** [computationalgeography/lue#608]
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

**Comment by OliverSchmitz** [comment]
- should this apply to the conda build as well?
- perhaps a bit too early, but is the Intel build still required?

**Comment by kordejong** [comment]
To recap our discussion:
- Indeed, the Conda build should also be updated to include the M1 runner.
- It is a good idea to get rid of the intel build. We must then also stop supporting it through Conda-Forge. I will add an issue for that on that side of Github.

**Comment by kordejong** [comment]
Mmm, if supporting M1 works, we might as well forget about fixing #611
