### ISSUE TITLE
Create issue template

### ISSUE THREAD

**Issue by kordejong** [computationalgeography/lue#610]
- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates

- Also a PR template?

**Comment by OliverSchmitz** [comment]
Duplicate of #534?

**Comment by kordejong** [comment]
Indeed. Closed the other one.
