### ISSUE TITLE
Verify licenses of 3rd party software are compatible with MIT

### ISSUE THREAD

**Issue by kordejong** [computationalgeography/lue#644]
LUE is licensed under the MIT license. This is only possible if licenses of software we depend on are compatible. This needs to be verified. Also, if 3rd party licenses require us to ship their license and copyright notices, we must start doing this.

**Comment by kordejong** [comment]
More info: https://gw-ospo.github.io/oss-licensing/intro.html

**Comment by saeb-faraji-gargari** [comment]
I will work on this.
