### ISSUE TITLE
[Bug]: to_gdal creates file with incorrect statistics

### ISSUE THREAD

**Issue by OliverSchmitz** [computationalgeography/lue#690]
### Describe the bug

In a script I only use `from_gdal` (reading a DEM) and `to_gdal`. The output TIFF receives
```
Band 1 Block=3081x1 Type=Float32, ColorInterp=Gray
  Min=436.726 Max=436.726 
  NoData Value=nan
  Metadata:
    STATISTICS_APPROXIMATE=YES
    STATISTICS_MAXIMUM=436.7262878418
    STATISTICS_MEAN=436.7262878418
    STATISTICS_MINIMUM=436.7262878418
    STATISTICS_STDDEV=0
    STATISTICS_VALID_PERCENT=84.03
```
which is clearly incorrect, min!=max in the data

### Additional information

On Linux

**Comment by kordejong** [comment]
I downloaded some DEM and I can't reproduce the issue. Can you share the data and script maybe?

**Comment by kordejong** [comment]
Yes, can be closed. Nice, no work needed ;-)
